from email.policy import default
from django.db import models

# Create your models here.

class student_Work(models.Model):
    studentName = models.CharField(max_length = 50, default="")
    studentClass = models.CharField(max_length = 50, default="")
    studentId = models.CharField(max_length = 50, default="")
    subjectName = models.CharField(max_length = 50, default="")
    fileName = models.CharField(max_length = 50, default="")
    file = models.FileField()
    uploaded_at = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(default="")
    staffName = models.CharField(max_length = 50, default="")

class Class_one(models.Model):
    Student_Name = models.CharField(max_length = 50, default="")
    Student_Id = models.CharField(max_length = 50, default="")
    Father_Name = models.CharField(max_length = 50, default="")
    Mother_Name = models.CharField(max_length = 50, default="")
    Habitation = models.CharField(max_length = 50, default="")
    Aadhar_UID_No = models.CharField(max_length = 50, default="")
    DOA = models.CharField(max_length = 50, default="")
    DOB = models.CharField(max_length = 50, default="")
    Sex = models.CharField(max_length = 50, default="")
    Caste = models.CharField(max_length = 50, default="")
    Sub_Caste = models.CharField(max_length = 50, default="")
    Miority = models.CharField(max_length = 50, default="")
    BPL_No = models.CharField(max_length = 50, default="")
    DisAdvantage_Bhagyalakshmi_Bond_No = models.CharField(max_length = 50, default="")
    Admin_RTE = models.CharField(max_length = 50, default="")
    Class_Studying = models.CharField(max_length = 50, default="")
    Previous_Class = models.CharField(max_length = 50, default="")
    Status_If = models.CharField(max_length = 50, default="")
    Medium = models.CharField(max_length = 50, default="")
    Sylabus = models.CharField(max_length = 50, default="")
    Disability = models.CharField(max_length = 50, default="")

class Class_two(models.Model):
    Student_Name = models.CharField(max_length = 50, default="")
    Student_Id = models.CharField(max_length = 50, default="")
    Father_Name = models.CharField(max_length = 50, default="")
    Mother_Name = models.CharField(max_length = 50, default="")
    Habitation = models.CharField(max_length = 50, default="")
    Aadhar_UID_No = models.CharField(max_length = 50, default="")
    DOA = models.CharField(max_length = 50, default="")
    DOB = models.CharField(max_length = 50, default="")
    Sex = models.CharField(max_length = 50, default="")
    Caste = models.CharField(max_length = 50, default="")
    Sub_Caste = models.CharField(max_length = 50, default="")
    Miority = models.CharField(max_length = 50, default="")
    BPL_No = models.CharField(max_length = 50, default="")
    DisAdvantage_Bhagyalakshmi_Bond_No = models.CharField(max_length = 50, default="")
    Admin_RTE = models.CharField(max_length = 50, default="")
    Class_Studying = models.CharField(max_length = 50, default="")
    Previous_Class = models.CharField(max_length = 50, default="")
    Status_If = models.CharField(max_length = 50, default="")
    Medium = models.CharField(max_length = 50, default="")
    Sylabus = models.CharField(max_length = 50, default="")
    Disability = models.CharField(max_length = 50, default="")

class Class_three(models.Model):
    Student_Name = models.CharField(max_length = 50, default="")
    Student_Id = models.CharField(max_length = 50, default="")
    Father_Name = models.CharField(max_length = 50, default="")
    Mother_Name = models.CharField(max_length = 50, default="")
    Habitation = models.CharField(max_length = 50, default="")
    Aadhar_UID_No = models.CharField(max_length = 50, default="")
    DOA = models.CharField(max_length = 50, default="")
    DOB = models.CharField(max_length = 50, default="")
    Sex = models.CharField(max_length = 50, default="")
    Caste = models.CharField(max_length = 50, default="")
    Sub_Caste = models.CharField(max_length = 50, default="")
    Miority = models.CharField(max_length = 50, default="")
    BPL_No = models.CharField(max_length = 50, default="")
    DisAdvantage_Bhagyalakshmi_Bond_No = models.CharField(max_length = 50, default="")
    Admin_RTE = models.CharField(max_length = 50, default="")
    Class_Studying = models.CharField(max_length = 50, default="")
    Previous_Class = models.CharField(max_length = 50, default="")
    Status_If = models.CharField(max_length = 50, default="")
    Medium = models.CharField(max_length = 50, default="")
    Sylabus = models.CharField(max_length = 50, default="")
    Disability = models.CharField(max_length = 50, default="")

class Class_four(models.Model):
    Student_Name = models.CharField(max_length = 50, default="")
    Student_Id = models.CharField(max_length = 50, default="")
    Father_Name = models.CharField(max_length = 50, default="")
    Mother_Name = models.CharField(max_length = 50, default="")
    Habitation = models.CharField(max_length = 50, default="")
    Aadhar_UID_No = models.CharField(max_length = 50, default="")
    DOA = models.CharField(max_length = 50, default="")
    DOB = models.CharField(max_length = 50, default="")
    Sex = models.CharField(max_length = 50, default="")
    Caste = models.CharField(max_length = 50, default="")
    Sub_Caste = models.CharField(max_length = 50, default="")
    Miority = models.CharField(max_length = 50, default="")
    BPL_No = models.CharField(max_length = 50, default="")
    DisAdvantage_Bhagyalakshmi_Bond_No = models.CharField(max_length = 50, default="")
    Admin_RTE = models.CharField(max_length = 50, default="")
    Class_Studying = models.CharField(max_length = 50, default="")
    Previous_Class = models.CharField(max_length = 50, default="")
    Status_If = models.CharField(max_length = 50, default="")
    Medium = models.CharField(max_length = 50, default="")
    Sylabus = models.CharField(max_length = 50, default="")
    Disability = models.CharField(max_length = 50, default="")

class Class_five(models.Model):
    Student_Name = models.CharField(max_length = 50, default="")
    Student_Id = models.CharField(max_length = 50, default="")
    Father_Name = models.CharField(max_length = 50, default="")
    Mother_Name = models.CharField(max_length = 50, default="")
    Habitation = models.CharField(max_length = 50, default="")
    Aadhar_UID_No = models.CharField(max_length = 50, default="")
    DOA = models.CharField(max_length = 50, default="")
    DOB = models.CharField(max_length = 50, default="")
    Sex = models.CharField(max_length = 50, default="")
    Caste = models.CharField(max_length = 50, default="")
    Sub_Caste = models.CharField(max_length = 50, default="")
    Miority = models.CharField(max_length = 50, default="")
    BPL_No = models.CharField(max_length = 50, default="")
    DisAdvantage_Bhagyalakshmi_Bond_No = models.CharField(max_length = 50, default="")
    Admin_RTE = models.CharField(max_length = 50, default="")
    Class_Studying = models.CharField(max_length = 50, default="")
    Previous_Class = models.CharField(max_length = 50, default="")
    Status_If = models.CharField(max_length = 50, default="")
    Medium = models.CharField(max_length = 50, default="")
    Sylabus = models.CharField(max_length = 50, default="")
    Disability = models.CharField(max_length = 50, default="")

class Class_six(models.Model):
    Student_Name = models.CharField(max_length = 50, default="")
    Student_Id = models.CharField(max_length = 50, default="")
    Father_Name = models.CharField(max_length = 50, default="")
    Mother_Name = models.CharField(max_length = 50, default="")
    Habitation = models.CharField(max_length = 50, default="")
    Aadhar_UID_No = models.CharField(max_length = 50, default="")
    DOA = models.CharField(max_length = 50, default="")
    DOB = models.CharField(max_length = 50, default="")
    Sex = models.CharField(max_length = 50, default="")
    Caste = models.CharField(max_length = 50, default="")
    Sub_Caste = models.CharField(max_length = 50, default="")
    Miority = models.CharField(max_length = 50, default="")
    BPL_No = models.CharField(max_length = 50, default="")
    DisAdvantage_Bhagyalakshmi_Bond_No = models.CharField(max_length = 50, default="")
    Admin_RTE = models.CharField(max_length = 50, default="")
    Class_Studying = models.CharField(max_length = 50, default="")
    Previous_Class = models.CharField(max_length = 50, default="")
    Status_If = models.CharField(max_length = 50, default="")
    Medium = models.CharField(max_length = 50, default="")
    Sylabus = models.CharField(max_length = 50, default="")
    Disability = models.CharField(max_length = 50, default="")

class Class_seven(models.Model):
    Student_Name = models.CharField(max_length = 50, default="")
    Student_Id = models.CharField(max_length = 50, default="")
    Father_Name = models.CharField(max_length = 50, default="")
    Mother_Name = models.CharField(max_length = 50, default="")
    Habitation = models.CharField(max_length = 50, default="")
    Aadhar_UID_No = models.CharField(max_length = 50, default="")
    DOA = models.CharField(max_length = 50, default="")
    DOB = models.CharField(max_length = 50, default="")
    Sex = models.CharField(max_length = 50, default="")
    Caste = models.CharField(max_length = 50, default="")
    Sub_Caste = models.CharField(max_length = 50, default="")
    Miority = models.CharField(max_length = 50, default="")
    BPL_No = models.CharField(max_length = 50, default="")
    DisAdvantage_Bhagyalakshmi_Bond_No = models.CharField(max_length = 50, default="")
    Admin_RTE = models.CharField(max_length = 50, default="")
    Class_Studying = models.CharField(max_length = 50, default="")
    Previous_Class = models.CharField(max_length = 50, default="")
    Status_If = models.CharField(max_length = 50, default="")
    Medium = models.CharField(max_length = 50, default="")
    Sylabus = models.CharField(max_length = 50, default="")
    Disability = models.CharField(max_length = 50, default="")

class Teachers_Info(models.Model): 
    Academic_Year = models.CharField(max_length = 50, default="")
    STS_Teacher_Id = models.CharField(max_length = 50, default="")
    KG_Id = models.CharField(max_length = 50, default="")
    Name = models.CharField(max_length = 50, default="")
    DOB = models.CharField(max_length = 50, default="")
    Gender = models.CharField(max_length = 50, default="") 
    Mobile_No = models.CharField(max_length = 50, default="")
    Status = models.CharField(max_length = 50, default="")
