# Generated by Django 5.0 on 2023-12-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(default='', max_length=50)),
                ('studentClass', models.CharField(default='', max_length=50)),
                ('studentId', models.CharField(default='', max_length=50)),
                ('subjectName', models.CharField(default='', max_length=50)),
                ('fileName', models.CharField(default='', max_length=50)),
                ('file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
