# Generated by Django 5.0 on 2023-12-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_work',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
