# Generated by Django 5.0 on 2023-12-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_App', '0003_class_five_class_four_class_one_class_seven_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_five',
            old_name='Medium_and_Sylabus',
            new_name='Medium',
        ),
        migrations.RenameField(
            model_name='class_four',
            old_name='Medium_and_Sylabus',
            new_name='Medium',
        ),
        migrations.RenameField(
            model_name='class_one',
            old_name='Medium_and_Sylabus',
            new_name='Medium',
        ),
        migrations.RenameField(
            model_name='class_seven',
            old_name='Medium_and_Sylabus',
            new_name='Medium',
        ),
        migrations.RenameField(
            model_name='class_six',
            old_name='Medium_and_Sylabus',
            new_name='Medium',
        ),
        migrations.RenameField(
            model_name='class_three',
            old_name='Medium_and_Sylabus',
            new_name='Medium',
        ),
        migrations.RenameField(
            model_name='class_two',
            old_name='Medium_and_Sylabus',
            new_name='Medium',
        ),
        migrations.AddField(
            model_name='class_five',
            name='Sylabus',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='class_four',
            name='Sylabus',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='class_one',
            name='Sylabus',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='class_seven',
            name='Sylabus',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='class_six',
            name='Sylabus',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='class_three',
            name='Sylabus',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='class_two',
            name='Sylabus',
            field=models.CharField(default='', max_length=50),
        ),
    ]
