# Generated by Django 5.0 on 2023-12-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_App', '0004_rename_medium_and_sylabus_class_five_medium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Academic_Year', models.CharField(default='', max_length=50)),
                ('STS_Teacher_Id', models.CharField(default='', max_length=50)),
                ('KG_Id', models.CharField(default='', max_length=50)),
                ('DOB', models.CharField(default='', max_length=50)),
                ('Gender', models.CharField(default='', max_length=50)),
                ('Mobile_No', models.CharField(default='', max_length=50)),
                ('Status', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
