# Generated by Django 5.0 on 2023-12-20 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School_App', '0007_classinfo_student_teachersinfo_studentclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeachersInfo',
        ),
    ]
