# Generated by Django 5.0 on 2023-12-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School_App', '0008_delete_teachersinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclass',
            name='classInfo',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='student',
        ),
        migrations.DeleteModel(
            name='ClassInfo',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentClass',
        ),
    ]
