# Generated by Django 5.0 on 2023-12-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_App', '0009_remove_studentclass_classinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_work',
            name='staffName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
